from __future__ import annotations

import logging
from typing import Any

import httpx

from app.auth.roles import ROLE_COLLECTIONS, UserRole
from app.db.vector_store import VectorStoreClient
from app.schemas.chat import SourceCitation

logger = logging.getLogger(__name__)


class LangChainHybridQAChain:
    def __init__(
        self,
        vector_store: VectorStoreClient,
        groq_api_key: str,
        groq_model: str,
        temperature: float = 0.0,
    ) -> None:
        self._vector_store = vector_store
        self._groq_api_key = groq_api_key
        self._groq_model = groq_model
        self._temperature = temperature

    @classmethod
    def create(
        cls,
        vector_store: VectorStoreClient,
        groq_api_key: str,
        groq_model: str,
        temperature: float = 0.0,
    ) -> LangChainHybridQAChain | None:
        if not groq_api_key.strip() or vector_store.langchain_vectorstore is None:
            return None

        try:
            #import langchain.chains  # noqa: F401
            import langchain_core.prompts  # noqa: F401
            import langchain_groq  # noqa: F401
        except ImportError:
            logger.info("LangChain hybrid QA chain dependencies missing; using fallback RAG path")
            return None

        return cls(
            vector_store=vector_store,
            groq_api_key=groq_api_key,
            groq_model=groq_model,
            temperature=temperature,
        )

    def run(self, question: str, role: UserRole, top_k: int = 5) -> tuple[str, list[SourceCitation]] | None:
        if self._vector_store.langchain_vectorstore is None:
            return None

        try:           
            from langchain.chains.retrieval import create_retrieval_chain
            from langchain.chains.combine_documents import create_stuff_documents_chain
            from langchain_core.prompts import ChatPromptTemplate
            from langchain_groq import ChatGroq
        except ImportError:
            logger.info("LangChain/Groq imports unavailable at runtime; using fallback RAG path")
            return None

        allowed_collections = set(ROLE_COLLECTIONS[role])

        # LangChain's HYBRID retrieval mode doesn't properly support Qdrant filters.
        # Workaround: retrieve MORE results without filter, then filter manually.
        retriever = self._vector_store.langchain_vectorstore.as_retriever(
            search_kwargs={"k": max(100, top_k * 5)}
        )
        
        def filtered_retriever(query: str) -> list:
            """Wrapper that retrieves documents and filters by role/collection."""
            docs = retriever.invoke(query)
            filtered = [
                doc for doc in docs
                if role.value in doc.metadata.get("access_roles", [])
                and doc.metadata.get("collection") in allowed_collections
            ]
            return filtered[:top_k]

        try:
            llm = ChatGroq(
                api_key=self._groq_api_key,
                model=self._groq_model,
                temperature=self._temperature,
                max_tokens=None,
                timeout=None,
                max_retries=2,
                http_client=httpx.Client(verify=False)
            )
        except Exception as exc:
            logger.warning("LangChain ChatGroq init failed; falling back to classic hybrid flow: %s", exc)
            return None

        system_prompt = (
            "You are MediBot assistant. Use only the provided context. "
            "If context is insufficient, say that clearly and do not fabricate details."
        )
        prompt = ChatPromptTemplate.from_messages(
            [
                ("system", system_prompt),
                ("human", "{input}"),
            ]
        )

        try:
            question_answer_chain = create_stuff_documents_chain(llm, prompt)
            # Use filtered retriever instead of retriever with broken filter
            hybrid_rag_chain = create_retrieval_chain(filtered_retriever, question_answer_chain)
            result: dict[str, Any] = hybrid_rag_chain.invoke({"input": question})
        except Exception as exc:
            logger.warning("LangChain retrieval invoke failed; falling back to classic hybrid flow: %s", exc)
            return None

        answer = str(result.get("answer", "")).strip() or "No response generated by retrieval chain."
        context_docs = list(result.get("context", []))

        citations: list[SourceCitation] = []
        for doc in context_docs:
            metadata = getattr(doc, "metadata", {}) or {}
            citations.append(
                SourceCitation(
                    source_document=str(metadata.get("source_document", "unknown")),
                    section_title=str(metadata.get("section_title", "No Heading")),
                    collection=str(metadata.get("collection", "general")),
                )
            )

        return answer, citations
