from __future__ import annotations

import logging
import re
from typing import Protocol

import requests

logger = logging.getLogger(__name__)


class LLMClient(Protocol):
    def generate(self, prompt: str) -> str:
        ...


class GroqLLMClient:
    """Production client that calls Groq Chat Completions API."""

    def __init__(self, api_key: str, model: str, temperature: float = 0.1, timeout_seconds: int = 60) -> None:
        if not api_key.strip():
            raise ValueError("GROQ_API_KEY is required to use GroqLLMClient")

        self._api_key = api_key
        self._model = model
        self._temperature = temperature
        self._timeout_seconds = timeout_seconds
        self._endpoint = "https://api.groq.com/openai/v1/chat/completions"

    def generate(self, prompt: str) -> str:
        logger.info(
            "GroqLLMClient.generate called model=%s temperature=%s prompt_chars=%s",
            self._model,
            self._temperature,
            len(prompt),
        )
        headers = {
            "Authorization": f"Bearer {self._api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self._model,
            "temperature": self._temperature,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You are MediBot assistant. Use only the supplied prompt context and "
                        "be concise and factual."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
        }

        response = requests.post(
            self._endpoint,
            headers=headers,
            json=payload,
            timeout=self._timeout_seconds,
        )
        logger.info("Groq HTTP response status=%s", response.status_code)
        response.raise_for_status()
        data = response.json()

        choices = data.get("choices", [])
        if not choices:
            logger.warning("Groq response returned no choices")
            return "No response generated by Groq model."

        message = choices[0].get("message", {})
        logger.info("Groq response content chars=%s", len(str(message.get("content", ""))))
        return str(message.get("content", "No response generated by Groq model.")).strip()


class StubLLMClient:
    """Non-production fallback. Replace with cloud-hosted providers in deployment."""

    def generate(self, prompt: str) -> str:
        logger.info("StubLLMClient.generate called prompt_chars=%s", len(prompt))
        prompt_lower = prompt.lower()
        if "generate a sqlite select query" in prompt_lower:
            logger.info("StubLLMClient returning canned SQL query")
            return "SELECT * FROM claims LIMIT 5"

        if "summarize these sqlite query results" in prompt_lower:
            logger.info("StubLLMClient returning canned SQL summary")
            return "The latest operational rows have been summarized from the SQL result set."

        logger.info("StubLLMClient generating context-based fallback answer")
        return self._answer_from_context(prompt)

    def _answer_from_context(self, prompt: str) -> str:
        question, context = self._extract_question_and_context(prompt)
        if not context.strip():
            return (
                "I do not have enough policy context to answer this question confidently: "
                f"{question or 'no question provided'}."
            )

        query_terms = self._keywords(question)
        sentences = self._sentences(context)
        if not sentences:
            return (
                "I do not have enough policy context to answer this question confidently: "
                f"{question or 'no question provided'}."
            )

        ranked = sorted(
            sentences,
            key=lambda sentence: self._sentence_score(sentence, query_terms),
            reverse=True,
        )

        top = [s for s in ranked if s.strip()][:2]
        if not top:
            return (
                "I do not have enough policy context to answer this question confidently: "
                f"{question or 'no question provided'}."
            )

        return " ".join(top)

    @staticmethod
    def _extract_question_and_context(prompt: str) -> tuple[str, str]:
        question_match = re.search(r"Question:\s*(.*?)\n\s*\nContext:\s*", prompt, flags=re.DOTALL)
        context_match = re.search(r"Context:\s*(.*)$", prompt, flags=re.DOTALL)
        question = question_match.group(1).strip() if question_match else ""
        context = context_match.group(1).strip() if context_match else ""
        return question, context

    @staticmethod
    def _keywords(text: str) -> set[str]:
        return {
            token
            for token in re.findall(r"[a-zA-Z][a-zA-Z0-9_]{2,}", text.lower())
            if token not in {"the", "and", "for", "with", "from", "that", "this", "are", "was", "were"}
        }

    @staticmethod
    def _sentences(text: str) -> list[str]:
        parts = re.split(r"(?<=[.!?])\s+|\n+", text)
        return [part.strip() for part in parts if part.strip()]

    @staticmethod
    def _sentence_score(sentence: str, query_terms: set[str]) -> tuple[int, int]:
        sentence_terms = set(re.findall(r"[a-zA-Z][a-zA-Z0-9_]{2,}", sentence.lower()))
        overlap = len(sentence_terms.intersection(query_terms))
        return overlap, min(len(sentence), 240)
