from __future__ import annotations

import logging
import re
from typing import Protocol
import httpx
import os
#import optparse

import requests

logger = logging.getLogger(__name__)


class LLMClient(Protocol):
    def generate(self, prompt: str) -> str:
        ...


class GroqLLMClient:
    """Production client that calls Groq Chat Completions API."""

    def __init__(self, api_key: str, model: str, temperature: float = 0.1, timeout_seconds: int = 60) -> None:
        if not api_key.strip():
            raise ValueError("GROQ_API_KEY is required to use GroqLLMClient")

        self._api_key = api_key
        self._model = model
        self._temperature = temperature
        self._timeout_seconds = timeout_seconds
        self._endpoint = "https://api.groq.com/openai/v1/chat/completions"

         # verify=False disables SSL check, or pass path to corporate cert
        self._client = httpx.Client(
            verify  = os.getenv("REQUESTS_CA_BUNDLE", False),
            timeout = timeout_seconds,
        )

    def generate(self, prompt: str) -> str:
        logger.info(
            "GroqLLMClient.generate called model=%s temperature=%s prompt_chars=%s",
            self._model,
            self._temperature,
            len(prompt),
        )
        headers = {
            "Authorization": f"Bearer {self._api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self._model,
            "temperature": self._temperature,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You are an Healthcare assistant. Use only the supplied prompt context and "
                        "be concise and factual."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
        }

        response = self._client.post(
            self._endpoint,
            headers=headers,
            json=payload,
        )
        
        logger.info("Groq HTTP response status=%s", response.status_code)
        response.raise_for_status()
        data = response.json()

        choices = data.get("choices", [])
        if not choices:
            logger.warning("Groq response returned no choices")
            return "No response generated by Groq model."

        message = choices[0].get("message", {})
        logger.info("Groq response content chars=%s", len(str(message.get("content", ""))))
        return str(message.get("content", "No response generated by Groq model.")).strip()
